### PR TITLE
Addded Extra fields

### PR DESCRIPTION
**Pull request by amanbolat**
#10 like it was said here, it would be nice to have `Extra` fields that will be always sent with this hook.

### CODE REVIEW

**Comment by amanbolat** [comment]
I don’t think, that it will break something. You still can leave Extra fields empty and fire the hook.

**Comment by johntdyer** [comment]
Last request, can you add to the readme with an example of its use

**Comment by johntdyer** [comment]
Awesome, thanks so much for the PR

**Comment by amanbolat** [comment]
@johntdyer thank you too, for accepting my PR :)
I'm new to open source, making some small steps

**Pull request merged**
